# Generated by Django 3.1.6 on 2021-05-01 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gellary', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagealbum',
            name='content',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='imagealbum',
            name='cover_image',
            field=models.ImageField(upload_to='photos/%Y/%m/%d/'),
        ),
    ]
