# Generated by Django 3.1.6 on 2021-05-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gellary', '0002_auto_20210502_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imagealbum',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
