# Generated by Django 3.1.6 on 2021-05-01 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gellary', '0003_auto_20210502_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagealbum',
            name='cover_image',
        ),
        migrations.RemoveField(
            model_name='imagealbum',
            name='image',
        ),
    ]
