# Generated by Django 3.1.6 on 2021-05-02 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gellary', '0004_auto_20210502_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='imagealbum',
            name='image',
            field=models.ImageField(default=1, upload_to=''),
            preserve_default=False,
        ),
    ]
