# Generated by Django 3.1.6 on 2021-05-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gellary', '0005_imagealbum_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagealbum',
            name='image',
        ),
    ]
