# Generated by Django 3.1.6 on 2021-05-03 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gellary', '0008_auto_20210502_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagealbum',
            name='content',
        ),
    ]
